version: "3"

services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:19283:${APACHE_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NEO4J_BOLT_ADDR: "host.docker.internal:17687"
      # APACHE_PORT задаётся в .env файле
      APACHE_PORT: ${APACHE_PORT}
      DEBUG: 1

    volumes:
      - "./static_data:/var/www/html/data:ro"
      # TODO: логи можно выводить в stderr, они появятся в docker
      #- "/root/site_log:/app/site_log"

